import { slugify } from "@/lib/helpers";

export const encodedBody = {
  suv: "SUV",
  truck: "Truck",
  sedan: "Sedan",
  van: "VAN",
  hatchback: "Hatchback",
  motorcycles: "Motorcycles",
  coupe: "Coupe",
  cabriolet: "Cabriolet",
  wagon: "Wagon",
  chassis: "Chassis",
}

const makeValues = [
  "Hyundai",
  "Honda",
  "Toyota",
  "Ford",
  "Subaru",
  "MAZDA",
  "Kia",
  "Ram",
  "Chevrolet",
  "Nissan",
  "Genesis",
  "Jeep",
  "Acura",
  "Ducati",
  "GMC",
  "Dodge",
  "Volkswagen",
  "BMW",
  "Chrysler",
  "Lexus",
  "Alfa Romeo",
  "Audi",
  "Cadillac",
  "Volvo",
  "Mercedes-Benz",
  "INFINITI",
  "Tesla",
  "Land Rover",
  "MINI",
  "Moto Guzzi",
  "Lincoln",
  "Mitsubishi",
  "Buick",
  "Harley-Davidson",
  "Kawasaki",
  "Porsche",
  "Yamaha",
  "Aprilia",
  "Indian Motorcycle",
  "Jaguar",
  "KTM",
  "Maserati",
  "Polestar",
  "Pontiac",
  "Rivian",
  "Scion",
  "Suzuki",
];

const modelValues = [
  "Crosstrek",
  "CR-V",
  "CX-5",
  "Cx-50",
  "1500",
  "2500",
  "Bronco Sport",
  "Civic",
  "3500",
  "Adx",
  "Cx-30",
  "Electrified Gv70",
  "4Runner",
  "Accord",
  "Elantra",
  "Colorado",
  "Equinox",
  "Bronco",
  "Ascent",
  "Camry",
  "Escape",
  "Carnival",
  "Charger",
  "Corolla",
  "Cx-90 Phev",
  "Durango",
  "Cx-90",
  "Altima",
  "Compass",
  "3500HD",
  "5500Hd",
  "Ariya",
  "Armada",
  "Corolla Cross",
  "Edge",
  "Equinox Ev",
  "Corvette",
  "Canyon",
  "Cherokee",
  "Civic Type R",
  "Diavel V4",
  "E-350sd",
  "Escalade",
  "300",
  "4500Hd",
  "Bz4X",
  "Crown",
  "Es",
  "4 Series",
  "4500 Hg Lcf",
  "5 Series",
  "5500 Hd Lcf",
  "A4",
  "Acadia",
  "Atlas",
  "Atlas Cross Sport",
  "Avalon",
  "Blazer Ev",
  "BRZ",
  "Challenger",
  "Cooper Countryman",
  "Cx-70",
  "CX-9",
  "Defender 110",
  "Desertx",
  "Elantra N",
  "2",
  "200",
  "3 Series",
  "390 Duke",
  "7 Series",
  "A4 Allroad",
  "A6",
  "Accent",
  "Africa Twin Dct",
  "Aviator",
  "Beetle",
  "Blazer",
  "Bolt Euv",
  "Brightdrop 600",
  "C-Hr",
  "C40 Recharge Pure",
  "Cayenne",
  "Cb1100",
  "Cb500F Abs",
  "Cooper S Clubman",
  "Cooper S Countryman",
  "Crown Signia",
  "Ct4",
  "CX-3",
  "Cx-70 Phev",
  "Cybertruck",
  "Defender 90",
  "Desertx Discovery",
  "Desertx Rally",
  "Discovery Sport",
  "E-Golf",
  "Element",
  "Enclave",
  "Envision",
];

const engineValues = [
  "2.5L 4-Cylinder DOHC 16V",
  "1.6L I4 DGI Hybrid Turbocharged DOHC 16V LEV3-SULEV30",
  "2.5L I4",
  "2.5L DOHC",
  "2.0L I4 DOHC 16V",
  "2.5L 4-Cylinder",
  "1.5L DOHC",
  "2.4L 4-Cylinder",
  "2.0L I4 DOHC 16V i-VTEC",
  "2.0L I4 DOHC",
  "1.5L I4 DOHC 16V",
  "1.5L EcoBoost",
  "2.5L 4-Cylinder DOHC Dual VVT-i",
  "1.5L I4 Turbocharged DOHC 16V LEV3-SULEV30",
  "2.0L 16V DOHC",
  "2.4L DOHC",
  "1.6L I4 DGI Hybrid DOHC 16V LEV3-SULEV30",
  "2.0L DOHC",
  "1.2L Ecotec Turbo DOHC DI w/VVT",
  "2.3L EcoBoost I-4",
  "2.4L 4-Cylinder DOHC 16V",
  "1.5T I4 DOHC 16V Turbocharged VTEC",
  "1.6L I4 DOHC 16V",
  "2.0L 4-Cylinder DOHC 16V",
  "2.5L 4-Cylinder DOHC 16V VVT",
  "1.3L I4",
  "2.0L I4 MPI",
  "2.0L Turbocharged",
  "2.4L I4 DOHC i-VTEC",
  "1.3L Ecotec Turbo DOHC SIDI w/VVT",
  "2.4L I4 DOHC 16V i-VTEC",
  "2.4L I4 PDI Turbocharged DOHC 16V LEV3-SULEV30 265hp",
  "2.5L 4-Cylinder 16V DOHC",
  "1.6L Turbo GDI 4-Cylinder",
  "2.4L I4",
  "1.5L I-4 DI DOHC Turbocharged",
  "2.0L I4 PDI DOHC 16V LEV3-SULEV30 169hp",
  "2.5L I-4 Hybrid",
  "1.5L I4 Turbocharged DOHC 16V LEV3-SULEV30",
  "1.8L I4 SOHC 16V i-VTEC",
  "2.0L I4 Turbocharged",
  "2.0L I4 TwinPower Turbo",
  "2.0L TSI DOHC",
  "2.0L 4-Cylinder DOHC 16V i-VTEC",
  "2.0L 4-Cylinder TFSI",
  "2.4L I4 MultiAir",
  "2.5L 4-Cylinder DOHC",
  "1.5L I3 Turbocharged DOHC 12V LEV3-ULEV50 201hp",
  "1.6L 4-Cylinder",
  "1.6L 4-Cylinder DOHC 16V",
  "1.6L I4 DGI Turbocharged DOHC 16V ULEV II 175hp",
  "1.8L DOHC 16V VVT",
  "1.8L I4 DOHC",
  "1.8L I4 DOHC 16V",
  "2.0L 4-Cylinder",
  "2.0L I4 MPI DOHC 16V LEV3-ULEV70 147hp",
  "2.0L I4 TFSI DOHC",
  "2.0L I4 Turbocharged DOHC 16V LEV3-ULEV70",
  "2.4L I4 DGI DOHC 16V",
  "2.4L I4 PDI Hybrid Turbocharged DOHC 16V",
  "2.5L DGI",
  "1.5L I-3",
  "1.5L I4 DOHC VVT-i 16V",
  "1.5L I4 SMPI DOHC 16V LEV3-SULEV30",
  "1.6L I4 DGI",
  "1.6L I4 DGI 16V",
  "1.6L I4 DGI DOHC 16V",
  "1.6L I4 DGI Hybrid DOHC 16V",
  "1.6L I4 DOHC 16V Turbocharged",
  "1.6L I4 Turbo",
  "1.8L 4-Cylinder DOHC",
  "1.8L 4-Cylinder DOHC 16V Dual CVVT PZEV",
  "1.8L 4-Cylinder SMPI Hybrid DOHC",
  "1.8L I4 DOHC Dual VVT-i",
  "1.8L I4 SOHC 16V VTEC",
  "2.0L 4-Cylinder DOHC 16V Turbocharged",
  "2.0L DOHC Intercooled Turbocharged",
  "2.0L I4 DGI DOHC 16V Turbocharged",
  "2.0L I4 DGI DOHC Turbocharged",
  "2.0L I4 DGI Turbocharged",
  "2.0L I4 DI Turbocharged",
  "2.0L I4 DOHC CVVT",
  "2.0L I4 DOHC Dual CVVT",
  "2.0L I4 PDI Hybrid DOHC 16V LEV3-SULEV30 150hp",
  "2.0L I4 PDI Turbocharged DOHC 16V LEV3-ULEV70 248hp",
  "2.0L I4 Turbocharged DOHC 16V LEV3-ULEV50 268hp",
  "2.0L TGDI",
  "2.0L TSI",
  "2.3L I4 DOHC",
  "2.4L 4-Cylinder DGI 198 hp",
  "2.4L 4-Cylinder DI DOHC",
  "2.4L I4 DGI DOHC",
  "2.4L I4 DGI DOHC 16V ULEV II 185hp",
  "2.4L I4 MPI DOHC CVVT 16V PZEV Theta 2",
  "2.4L I4 MPI Hybrid Electric DOHC",
  "2.4L I4 PDI Hybrid Turbocharged DOHC 16V LEV3-SULEV30 274hp",
  "2.5L 4-Cylinder DGI DOHC VVT",
  "2.5L DOHC Intercooled High Boost Turbocharged",
  "2.5L DOHC Intercooled High-Boost DAVCS",
  "2.5L i-VCT",
];

export const makesCode = Object.fromEntries(
  makeValues.map((val) => [slugify(val), val])
);

export const modelsCode = Object.fromEntries(
  modelValues.map((val) => [slugify(val), val])
);

export const enginesCode = Object.fromEntries(
  engineValues.map((val) => [slugify(val), val])
);